### ISSUE TITLE
Crash in singleplayer world together with ReplayMod

### ISSUE THREAD

**Issue by MightyKnight** [senseiwells/ServerReplay#19]
Thank you for the quick and helpful response previously.

I'm so sorry, when I went right to trying it did actually crash.

## Reproduction
Trying to provide a minimal reproducible example, here is a crash report from a fresh instance:
1. All required mods installed: `fabric-api, fabric-kotlin, ServerReplay` and additionally the normal ReplayMod (version 2.6.14).
2. I opened a singleplayer world (Cheats need to be enabled). The clientside Replay recording started automatically.
3. I entered the command `replay start players @s`
-> It crashed immediately

The singleplayer recording works correctly if just ServerReplay is installed, so the issue seems to be with an incompatibility.

## Crash report
<details>

<summary>
Click to expand crash report
</summary>

```

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-03-10 22:10:56
Description: Exception ticking world

java.lang.NoSuchMethodError: 'void com.replaymod.replaystudio.protocol.Packet.<init>(com.replaymod.replaystudio.protocol.PacketTypeRegistry, int, shadow.server_replay.com.github.steveice10.netty.buffer.ByteBuf)'
	at me.senseiwells.replay.recorder.ReplayRecorder.record(ReplayRecorder.kt:144)
	at net.minecraft.class_8609.handler$znl000$server-replay$onPacket(class_8609.java:1527)
	at net.minecraft.class_8609.method_52391(class_8609.java)
	at net.minecraft.class_8609.method_14364(class_8609.java:113)
	at net.minecraft.class_3898$class_3208.method_18730(class_3898.java:1343)
	at net.minecraft.class_3231.method_18756(class_3231.java:213)
	at net.minecraft.class_3898.method_18727(class_3898.java:1222)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:341)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.senseiwells.replay.recorder.ReplayRecorder.record(ReplayRecorder.kt:144)
	at net.minecraft.class_8609.handler$znl000$server-replay$onPacket(class_8609.java:1527)
	at net.minecraft.class_8609.method_52391(class_8609.java)
	at net.minecraft.class_8609.method_14364(class_8609.java:113)
	at net.minecraft.class_3898$class_3208.method_18730(class_3898.java:1343)
	at net.minecraft.class_3231.method_18756(class_3231.java:213)
	at net.minecraft.class_3898.method_18727(class_3898.java:1222)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)

-- Affected level --
Details:
	All players: 1 total; [class_3222['PlayerName'/1, l='ServerLevel[ServerReplay Test]', x=4.53, y=-60.00, z=18.54]]
	Chunk stats: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 436 game time, 436 day time
	Level name: ServerReplay Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 126491 (now: false), thunder time: 32666 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 13
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1681)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:951)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 454223800 bytes (433 MiB) / 1140850688 bytes (1088 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 4.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 73646.31
	Virtual memory used (MB): 29727.46
	Swap memory total (MB): 40960.00
	Swap memory used (MB): 319.68
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.96.4+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.14+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.3+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.3+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.1+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.25+58f8c0124f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.8+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.64+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.13+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.19+58f8c0124f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.19+58f8c0124f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		replaymod: Replay Mod 1.20.4-2.6.14
		server-replay: Server Replay Mod 1.0.7
			fabric-permissions-api-v0: fabric-permissions-api 0.3-SNAPSHOT
	Server Running: true
	Player Count: 1 / 8; [class_3222['PlayerName'/1, l='ServerLevel[ServerReplay Test]', x=4.53, y=-60.00, z=18.54]]
	Data Packs: vanilla, fabric, fabric-convention-tags-v1
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.7-1.20.4
```

</details>

Or as the uploaded file:
[crash-2024-03-10_22.10.56-server.txt](https://github.com/senseiwells/ServerReplay/files/14551806/crash-2024-03-10_22.10.56-server.txt)

## Version info
**Minecraft:** 1.20.4
**Fabric loader:** 0.15.7
**Fabric API:** 0.96.4-1.20.4
**Replaymod:** 2.6.14-1.20.4
**ServerReplay:** 1.0.7-mc1.20.4

Hope this helps, feel free to contact me anytime for further information or if you need me to test something.

**Comment by senseiwells** [comment]
Please try [this version](https://filebin.net/gx8m4iw0pyshpi7i/ServerReplay-1.0.8_mc1.20.4.jar)!

Let me know if you run into any further issues.

**Comment by TheSteeller** [comment]
the link is not adavaible ^^'

**Comment by senseiwells** [comment]
Sorry about that! 
It has now been released on Modrinth: https://modrinth.com/mod/server-replay/version/1.0.8+mc1.20.4
