### ISSUE TITLE
How do I prevent such errors?

### ISSUE THREAD

**Issue by copyandexecute** [senseiwells/ServerReplay#58]
```
[17:27:56] [DefaultDispatcher-worker-4/ERROR] (FabricLoader) Uncaught exception in thread "DefaultDispatcher-worker-4"
 io.netty.handler.codec.EncoderException: Sending unknown packet 'clientbound/minecraft:player_info_update'
	at net.minecraft.network.handler.PacketCodecDispatcher.encode(PacketCodecDispatcher.java:47) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.network.handler.PacketCodecDispatcher.encode(PacketCodecDispatcher.java:14) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at me.senseiwells.replay.recorder.ReplayRecorder.encodePacket(ReplayRecorder.kt:601) ~[ServerReplay-59ac3ec.jar:?]
	at me.senseiwells.replay.recorder.ReplayRecorder.record(ReplayRecorder.kt:202) ~[ServerReplay-59ac3ec.jar:?]
	at net.minecraft.server.network.ServerCommonNetworkHandler.handler$cgp000$server-replay$onPacket(ServerCommonNetworkHandler.java:2029) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.server.network.ServerCommonNetworkHandler.send(ServerCommonNetworkHandler.java) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.send(ServerPlayNetworkHandler.java:6646) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.server.network.ServerCommonNetworkHandler.sendPacket(ServerCommonNetworkHandler.java:143) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.server.PlayerManager.sendToAll(PlayerManager.java:560) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.changeGameMode(ServerPlayerInteractionManager.java:66) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at net.minecraft.server.network.ServerPlayerEntity.changeGameMode(ServerPlayerEntity.java:1562) ~[minecraft-merged-66a01aa42f-1.21-net.fabricmc.yarn.1_21.1.21+build.9.jar:?]
	at gg.norisk.subwaysurfers.server.mechanics.SpectateManager$init$1.invokeSuspend(SpectateManager.kt:35) ~[main/:?]
	at gg.norisk.subwaysurfers.server.mechanics.SpectateManager$init$1.invoke(SpectateManager.kt) ~[main/:?]
	at gg.norisk.subwaysurfers.server.mechanics.SpectateManager$init$1.invoke(SpectateManager.kt) ~[main/:?]
	at net.silkmc.silk.network.packet.AbstractPacketDefinition$onReceive$1.invokeSuspend(PacketDefinition.kt:49) ~[silk-network-1.10.7.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-2.0.10.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) [kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
```

**Comment by copyandexecute** [comment]
wtf

**Comment by copyandexecute** [comment]
there was a sketchy answer its gone

**Comment by senseiwells** [comment]
I deleted the message and reported them - there seem to be an increase of phishing messages, please do not trust any downloads. I am the only maintainer of this mod.

It seems some other mod is sending packets off-thread which is breaking ServerReplay. Could you provide more context for this issue? My guess would be this happened as a player joined the world?

**Comment by copyandexecute** [comment]
> It seems some other mod is sending packets off-thread which is breaking ServerReplay. Could you provide more context for this issue? My guess would be this happened as a player joined the world?

Oh thanks alot, this was indeed the case <3
