### ISSUE TITLE
Player can't join the server after enabling auto recording

### ISSUE THREAD

**Issue by Realzhazha** [senseiwells/ServerReplay#60]
Players can't join the server after enabling auto recording, the problem seems to be "tried to get player before player joined"?
Here is the server log, some date, time, player name and IP address are replaced but I believe this is still useful
```
[Server] [HH:MM:SS] [User Authenticator #1/INFO]: UUID of player PlayerName is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Server] [HH:MM:SS] [Netty Server IO #1/INFO]: Started replay for PlayerName
[Server] [HH:MM:SS] [Server thread/INFO]: PlayerName[/xxx.xxx.x.xxx:xxxx] logged in with entity id xx at (xxx.xxxxxxxxxxxxx, xx.xxxxxxxxxxxxx, xxx.xxxxxxxxxxxxx)
[Server] [HH:MM:SS] [Server thread/INFO]: [Essential Commands] Loading PlayerData for player with uuid 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'.
[Server] [HH:MM:SS] [Server thread/ERROR]: Couldn't place player in world
[Server] java.lang.IllegalStateException: Tried to get player before player joined
[Server]        at me.senseiwells.replay.player.PlayerRecorder.getPlayerOrThrow(PlayerRecorder.kt:75) ~[ServerReplay-1.1.2+mc1.20.4.jar:?]
[Server]        at me.senseiwells.replay.player.PlayerRecorder.getLevel(PlayerRecorder.kt:50) ~[ServerReplay-1.1.2+mc1.20.4.jar:?]
[Server]        at me.senseiwells.replay.util.ReplayOptimizerUtils.optimiseEntity(ReplayOptimizerUtils.kt:115) ~[ServerReplay-1.1.2+mc1.20.4.jar:?]
[Server]        at me.senseiwells.replay.util.ReplayOptimizerUtils.optimisePackets(ReplayOptimizerUtils.kt:79) ~[ServerReplay-1.1.2+mc1.20.4.jar:?]
[Server]        at me.senseiwells.replay.recorder.ReplayRecorder.record(ReplayRecorder.kt:185) ~[ServerReplay-1.1.2+mc1.20.4.jar:?]
[Server]        at net.minecraft.class_8609.handler$ece000$server-replay$onPacket(class_8609.java:3529) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_8609.method_52391(class_8609.java) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_52391(class_3244.java:11051) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_8609.method_14364(class_8609.java:113) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3324.method_14596(class_3324.java:648) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3324.method_14576(class_3324.java:551) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3324.method_14570(class_3324.java:198) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_8610.method_52408(class_8610.java:128) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_8736.method_53043(class_8736.java:20) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_8736.method_11054(class_8736.java:7) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.wrapOperation$cgn000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[Server] [HH:MM:SS] [Server thread/INFO]: PlayerName lost connection: Invalid player data
[Server] [HH:MM:SS] [Server thread/INFO]: PlayerName left the game
[Server] [HH:MM:SS] [pool-8-thread-1/INFO]: Starting to save replay PlayerName, please do not stop the server!
[Server] [HH:MM:SS] [pool-8-thread-1/INFO]: Successfully closed replay PlayerName and saved to .\recordings\players\PlayerName\YYYY-MM-DD--HH-MM-SS.mcpr, compressed to xx.x KiB
```

**Comment by tryptophawa** [comment]
try disable optimize_entity_packets
seems like this setting conflict with lithium

**Comment by tryptophawa** [comment]
i met this issue before
